---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url:
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _galleries
  label: Galleries
  create: all
  match: "**/*"
- type: directory
  path: _new
  label: New
  create: all
  match: "**/*"
  templates:
  - new-frontmatter
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
- type: directory
  path: _works
  label: Works
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
